# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2ab95ba99ea07378a78907882c10b6f949975d78187882027691b578eb08834343469b181dea144833c0ec7bd40e9c315ec29535f19cda2495e2de8cf732a5e

test:
  secret_key_base: 57e3f321d60cf7d6060cf5a9a61621c691708148d93cb1b8c4139b6324449431af8b420f9d21148945981f533f8539c207035e49b5bd8c120c094881d8a0fad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
